public enum RuntimeEnvironmentKey {
    public static let noDesktop = "IRIDIUM_NO_DESKTOP"
    public static let hostJITStatus = "IRIDIUM_HOST_JIT_STATUS"
    public static let activeJITProvider = "IRIDIUM_FEX_IOS_ACTIVE_JIT_PROVIDER"
    public static let debuggerRegionProtocol = "IRIDIUM_FEX_IOS_DEBUGGER_REGION_PROTOCOL"
    public static let runtimeBundleRoot = "IRIDIUM_RUNTIME_BUNDLE_ROOT"
    public static let runtimeBundleID = "IRIDIUM_RUNTIME_BUNDLE_ID"
    public static let runtimeBundleVersion = "IRIDIUM_RUNTIME_BUNDLE_VERSION"
    public static let runtimeGraphicsStack = "IRIDIUM_RUNTIME_GRAPHICS_STACK"
    public static let rendererPreset = "IRIDIUM_RENDERER_PRESET"
    public static let shaderStrategy = "IRIDIUM_SHADER_STRATEGY"
    public static let memoryBudget = "IRIDIUM_MEMORY_BUDGET"
    public static let frameCap = "IRIDIUM_FRAME_CAP"
    public static let resolutionScale = "IRIDIUM_RESOLUTION_SCALE"
    public static let prefixManifest = "IRIDIUM_PREFIX_MANIFEST"
    public static let userlandRoot = "IRIDIUM_USERLAND_ROOT"
    public static let wineServerRoot = "IRIDIUM_WINE_SERVER_ROOT"
    public static let wineDataDirectory = "WINEDATADIR"

    public static let wineIOSSurfaceID = "IRIDIUM_WINE_IOS_SURFACE_ID"
    public static let wineIOSBridgeRoot = "IRIDIUM_WINE_IOS_BRIDGE_ROOT"
    public static let wineIOSBridgeConfig = "IRIDIUM_WINE_IOS_BRIDGE_CONFIG"
    public static let wineIOSFramebufferPath = "IRIDIUM_WINE_IOS_FRAMEBUFFER_PATH"
    public static let wineIOSInputEventsPath = "IRIDIUM_WINE_IOS_INPUT_EVENTS_PATH"
    public static let wineIOSAudioStatePath = "IRIDIUM_WINE_IOS_AUDIO_STATE_PATH"
    public static let wineIOSTracePath = "IRIDIUM_WINE_IOS_TRACE_PATH"
    public static let wineIOSGraphicsDriver = "IRIDIUM_WINE_IOS_GRAPHICS_DRIVER"
    public static let wineIOSAudioDriver = "IRIDIUM_WINE_IOS_AUDIO_DRIVER"
    public static let wineIOSSurfaceWidth = "IRIDIUM_WINE_IOS_SURFACE_WIDTH"
    public static let wineIOSSurfaceHeight = "IRIDIUM_WINE_IOS_SURFACE_HEIGHT"

    public static let hostTelemetryAverageFPS = "IRIDIUM_HOST_TELEMETRY_AVERAGE_FPS"
    public static let hostTelemetryFrameTimeP95MS = "IRIDIUM_HOST_TELEMETRY_FRAME_TIME_P95_MS"
    public static let hostTelemetryMemoryPressureRatio = "IRIDIUM_HOST_TELEMETRY_MEMORY_PRESSURE_RATIO"
    public static let hostTelemetryThermalState = "IRIDIUM_HOST_TELEMETRY_THERMAL_STATE"
}
