#!/bin/bash
# Prepare missing tools, refresh changed runtime inputs, then build incrementally.
set -Eeuo pipefail
cd "$(dirname "$0")/.."
mkdir -p .build/local-build-logs
log="$PWD/.build/local-build-logs/build-$(date +%Y%m%d-%H%M%S)-$$.log"
exec > >(tee "$log") 2>&1
trap 'status=$?; printf "Local IPA build failed (exit %s) at line %s.\nFull log: %s\n" "$status" "$LINENO" "$log" >&2; exit "$status"' ERR
printf 'Full build log: %s\n' "$log"
python3 ci/local_build_tools.py --write-env .build/local-build-tools.env
# Generated by our preflight; values are shell-quoted, never Homebrew shell output.
source .build/local-build-tools.env
python3 ci/prepare-local-runtime.py
python3 ci/check-local-runtime-provenance.py
python3 ci/check-ipa-prerequisites.py
runtime_resources=iridium/packages/runtime/Sources/IridiumRuntime/Resources/BundledRuntime
mkdir -p "$runtime_resources"
rm -rf "$runtime_resources/iridium-runtime-base"
ditto iridium-runtime-sdk/build/iridium-runtime-base "$runtime_resources/iridium-runtime-base"
python3 ci/prepare-stikjit-interface.py
xcodegen generate --spec iridium/apps/ios/stikjit.yml
xcodebuild -project iridium/apps/ios/IridiumStikJIT.xcodeproj \
  -scheme Iridium -configuration Release -destination 'generic/platform=iOS' \
  -derivedDataPath .build/local-ipa \
  CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= \
  DEVELOPMENT_TEAM= EXPANDED_CODE_SIGN_IDENTITY= \
  PROVISIONING_PROFILE_SPECIFIER= PROVISIONING_PROFILE= \
  IPHONEOS_DEPLOYMENT_TARGET=27.0 LD_GENERATE_MAP_FILE=YES build
app=.build/local-ipa/Build/Products/Release-iphoneos/Iridium.app
objcopy="$(brew --prefix llvm)/bin/llvm-objcopy"
echo 'Removing Windows debug sections from the packaged app copy.'
for arch in arm64ec aarch64; do
  while IFS= read -r -d '' module; do
    if [ "$(head -c 2 "$module")" = MZ ]; then
      "$objcopy" --strip-debug "$module"
    fi
  done < <(find "$app/$arch-windows" -type f -print0)
done
python3 ci/check-ipa-prerequisites.py --package
output=$(mktemp -d "$PWD/.build/local-ipa-output.XXXXXX")
python3 ci/package-unsigned-ipa.py \
  "$app" "$output"
printf 'IPA: %s/Iridium-unsigned.ipa\n' "$output"
