#!/usr/bin/env python3
"""Verify or regenerate SameBoy's upstream replacement boot-ROM build inputs."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import tempfile

REVISION = '208ba4afabffab9edde416f2dbb8ae459e34adb8'
RGBDS_REVISION = 'd1829ed92327a9f9210ffd45d865331f24dfa4e6'
RGBDS_VERSION = 'v0.9.4'
MODELS = {'agb': 2304, 'cgb': 2304, 'cgb0': 2304, 'dmg': 256,
          'mgb': 256, 'sgb': 256, 'sgb2': 256}
ROOT = Path(__file__).resolve().parents[1]
MANIFEST = Path(__file__).with_name('sameboy-bootroms.json')


def digest(data):
    return hashlib.sha256(data).hexdigest()


def source_hashes(core):
    paths = [core / 'Makefile', core / 'version.mk', *sorted((core / 'BootROMs').iterdir())]
    if any(path.is_symlink() or not path.is_file() for path in paths):
        raise ValueError('Unexpected upstream boot-ROM source layout')
    return {path.relative_to(core).as_posix(): digest(path.read_bytes()) for path in paths}


def read_bootroms(core, manifest=MANIFEST):
    record = json.loads(manifest.read_text())
    if (record.get('revision') != REVISION or record.get('rgbdsRevision') != RGBDS_REVISION
            or record.get('rgbdsVersion') != RGBDS_VERSION
            or record.get('sourceSHA256') != source_hashes(core)
            or set(record.get('bootROMs', {})) != set(MODELS)):
        raise ValueError('Replacement boot-ROM provenance does not match the pinned source')
    result = {}
    for model, size in MODELS.items():
        item = record['bootROMs'][model]
        data = bytes.fromhex(''.join(item['hex']))
        if len(data) != size or digest(data) != item['sha256']:
            raise ValueError('Invalid replacement boot-ROM data: ' + model)
        result[model] = data
    return result


def regenerate(core, rgbds, output):
    # Explicit opt-in regeneration only. Ordinary app builds consume the reviewed
    # generated bytes; they do not install assemblers or download firmware.
    if output.exists() or output.is_symlink():
        raise ValueError('Choose a new output path; reviewed data is never overwritten')
    if (core / '.git').exists():
        source_revision = subprocess.check_output(['git', '-C', str(core), 'rev-parse', 'HEAD'], text=True).strip()
        changed_source = subprocess.check_output(['git', '-C', str(core), 'diff', '--name-only', 'HEAD'], text=True).strip()
        if source_revision != REVISION or changed_source:
            raise ValueError('Use unchanged pinned SameBoy source')
    elif json.loads((ROOT / 'SOURCE-REVISIONS.json').read_text()).get('vendor/SameBoy') != REVISION:
        raise ValueError('Source archive does not record the selected SameBoy revision')
    revision = subprocess.check_output(['git', '-C', str(rgbds), 'rev-parse', 'HEAD'], text=True).strip()
    changed = subprocess.check_output(['git', '-C', str(rgbds), 'diff', '--name-only', 'HEAD'], text=True).strip()
    if revision != RGBDS_REVISION or changed:
        raise ValueError('Use an unchanged checkout of the pinned RGBDS source')
    for tool in ('rgbasm', 'rgblink', 'rgbgfx'):
        version = subprocess.check_output([str(rgbds / tool), '--version'], text=True).strip()
        if version != tool + ' ' + RGBDS_VERSION:
            raise ValueError('Regeneration requires RGBDS ' + RGBDS_VERSION)
    before = source_hashes(core)
    with tempfile.TemporaryDirectory(prefix='sameboy-bootroms-') as temporary:
        stage = Path(temporary)
        subprocess.run(['make', '-C', str(core), 'bootroms', 'RGBDS=' + str(rgbds.resolve()) + '/',
                        'BIN=' + str(stage), 'OBJ=' + str(stage / 'obj'),
                        'PB12_COMPRESS=' + str(stage / 'pb12'), 'NATIVE_CC=cc'], check=True)
        if source_hashes(core) != before:
            raise ValueError('Boot-ROM generation changed upstream source')
        boots = {}
        for model, size in MODELS.items():
            data = (stage / 'BootROMs' / (model + '_boot.bin')).read_bytes()
            if len(data) != size:
                raise ValueError('Unexpected replacement boot-ROM size')
            encoded = data.hex()
            boots[model] = {'sha256': digest(data),
                            'hex': [encoded[i:i + 64] for i in range(0, len(encoded), 64)]}
        record = {'revision': REVISION, 'rgbdsRevision': RGBDS_REVISION,
                  'rgbdsVersion': RGBDS_VERSION, 'sourceSHA256': before, 'bootROMs': boots}
        # Never silently overwrite reviewed data; compare and replace separately.
        with output.open('x') as stream:
            stream.write(json.dumps(record, indent=2, sort_keys=True) + '\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--rgbds', type=Path, required=True, help='Directory containing RGBDS 0.9.4 tools')
    parser.add_argument('--output', type=Path, required=True, help='New JSON path, never overwritten')
    args = parser.parse_args()
    regenerate(ROOT / 'vendor/SameBoy', args.rgbds, args.output)
